version: '2'
services:
  web:
    image: nginx:1.11
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./src:/usr/share/nginx/html:ro
      - ./conf:/etc/nginx/conf.d
      - /etc/letsencrypt:/etc/nginx/ssl
